### ISSUE TITLE
Allow "area" keyword ?

### ISSUE THREAD

**Issue by steph-ben** [ecmwf/ecmwf-opendata#3]
Hi ECMWF,

Thanks for releasing opensource data and providing this python package !

I would like to access only data on a particular geographic area. That would : 
* limit bandwidth
* limit storage on my server

I try the following, inspired from  [ecmwf-api-client](https://github.com/ecmwf/ecmwf-api-client#example) : 
```
>>> from ecmwf.opendata import Client
>>> client = Client()
>>> r = client.retrieve(step=240, type="fc", param="msl", area="70/-130/30/-60", target="plop.grib2")
MARS post-processing keywords {'area'} not supported
```

Is there any plan to add the "area" keyword, or any other way to achieve this ?

Stéphane

**Comment by b8raoult** [comment]
Stéphane, unfortunately, the open data dataset is served by plain web servers and it is not possible to run any processing on the data server-side. You may want to check out other ECMWF software, such as metview, that provides python-based data manipulation tools.

**Comment by steph-ben** [comment]
Baudoin, thanks for your clear answer.

Actually once the file is downloaded, I'm fine for the processing (xarray does a great job as well!). The whole point was preventing to download useless amount of data.

As comparison, NOAA offers this subset service, as you might certainly be aware of : https://nomads.ncep.noaa.gov/cgi-bin/filter_gfs_0p25.pl

Anyway, that's already really nice from you providing both simple download from https://data.ecmwf.int & high-level python lib
