### ISSUE TITLE
Support the new 0.25 degree open data

### ISSUE THREAD

**Issue by djzurawski** [ecmwf/ecmwf-opendata#33]

**Comment by josepaulo1233** [comment]
How to select the 0.25 degree data instead 0p4? 

I tried 

```
client = Client(
    source="ecmwf",
    model="ifs",
    resol="0p25",
    preserve_request_order=False,
    infer_stream_keyword=True,
)
```

but both model and resol doesn't work.

**Comment by packman2008** [comment]
Check that you've got v0.3.0. When I looked earlier today Pypi still only had v0.2.0. I got the update from GitHub and manually copied the files. Resol and model worked OK.

**Comment by josepaulo1233** [comment]
I just copy and paste the new client.py file and that's works..
