### ISSUE TITLE
Radiation variables unavailable?

### ISSUE THREAD

**Issue by Edudiro** [ecmwf/ecmwf-opendata#37]
Variables like surface net radiation (ssr) don't seem to be available, eventhough in product description from [ecmwf](https://www.ecmwf.int/en/forecasts/datasets/open-data) they are described. 

Is this an issue on their side?

**Comment by mtoernerh** [comment]
The most recent forecast as of writing (https://data.ecmwf.int/forecasts/20240306/00z/ifs/0p25/oper/) has radiation fluxes.

**Comment by Edudiro** [comment]
This is great news! I can see several new variables added. Thanks
