### ISSUE TITLE
Corrupted index files for tp param

### ISSUE THREAD

**Issue by martimfj** [ecmwf/ecmwf-opendata#7]
Hello,

Some .index files for the ensemble models (that I've checked) have the param **tp** "corrupted". It is shown as "unknown". 

Example:
`{"domain": "g", "date": "20220222", "time": "0000", "expver": "0001", "class": "od", "type": "pf", "stream": "enfo", "levtype": "sfc", "number": "28", "step": "12", "param": "unknown", "_offset": 36341019, "_length": 812043}`

When specifying this param in the API, I get: 
> `Did you mean 'sp' instead of 'tp'?`

The problem is only on the index file. Passing "unknown" as a param, the grib file returns with the tp variable.

best regards

**Comment by milanavuckovic** [comment]
Hi Martin,
Thank you for reporting this issue. We've identified the problem and it has been fixed. The index files from 22/02/2022 at 12 and after are correct. 
If you run into another problem using ECMWF opendata, could you open a ticket at our support portal at: https://support.ecmwf.int/   
Many thanks,
Milana

**Comment by milanavuckovic** [comment]
Fixed
